service: serverless-boilerplate
frameworkVersion: "3"
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: "aws"
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
functions:
  jobCategoryGetList:
    handler: ./src/functions/jobCategory/handler.list
    events:
      - httpApi:
          method: GET
          path: /category
    memorySize: 128
package:
  individually: true
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
